Script started on 2021-04-07 17:15:14-04:00 [TERM="xterm-256color" TTY="/dev/pts/27" COLUMNS="236" LINES="58"]
]0;fkarim26@compute:~/courses/cs2211b/Asn/asn5[fkarim26@compute asn5]$ date
Wed 07 Apr 2021 05:15:18 PM EDT
]0;fkarim26@compute:~/courses/cs2211b/Asn/asn5[fkarim26@compute asn5]$ who am i 
fkarim26 pts/31       2021-04-07 17:15
]0;fkarim26@compute:~/courses/cs2211b/Asn/asn5[fkarim26@compute asn5]$ ls
balanceTree.c  BStree.c  BStree.h  cases.c  casesFunctions.c  definitions.h  fkarim26_asn5.script  headers.h  main.c  makefile  menu.c  populateTree.c  printTree.c
]0;fkarim26@compute:~/courses/cs2211b/Asn/asn5[fkarim26@compute asn5]$ make
gcc -c main.c
gcc -c menu.c
gcc -c cases.c
gcc -c casesFunctions.c
gcc -c BStree.c
gcc -c populateTree.c
gcc -c printTree.c
gcc -c balanceTree.c
gcc -o myBST main.o menu.o cases.o casesFunctions.o BStree.o populateTree.o printTree.o balanceTree.o
]0;fkarim26@compute:~/courses/cs2211b/Asn/asn5[fkarim26@compute asn5]$ ./myBST 

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: t

Failed, Tree is empty

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: !

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: o

Result of Inorder Traversal print:
1 2 3 4 5 7 8 9 10 12 14 16 17 18 22 25 27 32 

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: p

depth (1) -    10 
depth (2) -    4 18 
depth (3) -    3 5 12 22 
depth (4) -    2 x x 8 x 16 x 27 
depth (5) -    1 x x x 7 9 x 14 17 x 25 32 


=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: w i

Enter integer value to be inserted into the BST: 16

Node: 16 already exits

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: i

Enter integer value to be inserted into the BST: 11


=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: o

Result of Inorder Traversal print:
1 2 3 4 5 7 8 9 10 11 12 14 16 17 18 22 25 27 32 

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: x

Done, Tree deleted

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: #

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: r

Result of Preorder Traversal print:
1 2 3 4 5 6 

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: b p

depth (1) -    1 
depth (2) -    x 2 
depth (3) -    x x 3 
depth (4) -    x x x 4 
depth (5) -    x x x x 5 
depth (6) -    x x x x x 6 


=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: b

Tree is balanced


=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: p

depth (1) -    3 
depth (2) -    1 5 
depth (3) -    x 2 4 6 


=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: r

Result of Preorder Traversal print:
3 1 2 5 4 6 

=============== Menu ===============
 i: Insert         | o: In Order 
 d: Delete         | t: Post Order 
 p: Print          | r: Pre Order 
 n: No. of Leafs   | b: Balance Tree 
 x: Destroy Tree   | q: Quit 
 s: Search                       
====================================
Please enter your choice: q

FINISHED
]0;fkarim26@compute:~/courses/cs2211b/Asn/asn5[fkarim26@compute asn5]$ exit
exit

Script done on 2021-04-07 17:17:14-04:00 [COMMAND_EXIT_CODE="0"]
